grpc:
  server:
    port: 9090
    security:
      enabled: true
      certificate-chain: file:server-data/keys/tls-cert.pem
      private-key: file:server-data/keys/tls-key.pem
      trust-cert-collection: file:server-data/keys/ca-cert.pem
      client-auth: REQUIRE  # Mutual TLS

spring:
  application:
    name: deathnode-server
  datasource:
    # url: jdbc:postgresql://192.168.0.200:5432/deathnode?ssl=true&sslmode=verify-full&sslrootcert=server-data/keys/ca-cert.pem&sslcert=server-data/keys/tls-cert.pem&sslkey=server-data/keys/tls-key.pem # VM
    url: jdbc:postgresql://127.0.0.1:5432/deathnode?ssl=true&sslmode=verify-full&sslrootcert=server-data/db-client/ca-cert.pem&sslcert=server-data/db-client/client-cert.pem&sslkey=server-data/db-client/client-key.pk8
    username: dn_admin
    password: dn_pass
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: false

  sql:
    init:
      mode: never
  
storage:
  envelopes-path: server-data/

keystore_path: server-data/keys/keystore.jks
keystore_password: demonstration
ed_private_key_alias: sign-key
rsa_private_key_alias: rsa-key